### ISSUE TITLE
Installation failes due to mu4e as a package requirement

### ISSUE THREAD

**Issue by danielfleischer** [armindarvish/consult-mu#34]
**Describe the bug**
Can't install `consult-mu` because of the added `(mu4e "1.10.8")` requirement not being fulfilled.

**To Reproduce**
Try to install the package using a github installer, e.g. Quelpa.

**Additional context**
mu4e is special; it is typically installed by installing mu (either from source or compiled) and the mu4e elisp files are put in some shared location and `:load-path` is used; that's why Emacs doesn't see it as an installed package, it is not in `package-selected-packages` and the requirements check is failing.

**Comment by armindarvish** [comment]
@danielfleischer I removed mu4e as a package requirement and simply added a comment mentioning the dependency. See if that resolves your issue

**Comment by danielfleischer** [comment]
Thank you, it works. 

One can implement some other mechanism for checking dependency, either searching `mu` using `executable-find` or trying to see if mu4e is in the `features` variable. Just examples.

Can close.
